---
version: '3.2'
services:
  testacc:
    build: .
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9090,kafka2:9090,kafka3:9090
    entrypoint:
      - make
      - testacc
    depends_on:
      - kafka1
      - kafka2
      - kafka3
